import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  date,
  doublePrecision,
  index,
  integer,
  pgEnum,
  pgTable,
  smallint,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

import { user } from './auth-schema';

// Auth tables (user, session, account, verification) are generated by the
// Better Auth CLI into auth-schema.ts so they always match the installed
// version. Domain tables below mirror src/store/types.ts and the rules in
// README "Domain rules": soft deletion via deleted_at, immutable check-ins
// unique per (pact, user, date), days_of_week 0=Sunday…6=Saturday, local
// YYYY-MM-DD date keys, IANA timezones first-class.
export * from './auth-schema';

export const friendshipStatus = pgEnum('friendship_status', [
  'pending',
  'accepted',
  'declined',
  'blocked',
]);
export const pactType = pgEnum('pact_type', ['frequency', 'goal']);
// 'pending' and 'declined' are the Proposal states (ADR-0006): only MUTUAL
// pacts ever carry them — a solo pact is never a proposal. They are appended
// (not inserted in lifecycle order) so drizzle-kit diffs to plain
// `ALTER TYPE … ADD VALUE` statements instead of recreating the type.
export const pactStatus = pgEnum('pact_status', [
  'active',
  'completed',
  'incomplete',
  'cancelled',
  'pending',
  'declined',
]);
export const checkInStatus = pgEnum('check_in_status', ['completed', 'failed']);
export const notificationType = pgEnum('notification_type', [
  'daily_reminder',
  'friend_request',
  'friend_accepted',
  'pact_breach',
  'pact_completed',
]);

const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
};

export const friendships = pgTable(
  'friendships',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    requesterId: text('requester_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    addresseeId: text('addressee_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    status: friendshipStatus('status').default('pending').notNull(),
    ...timestamps,
  },
  (t) => [
    index('friendships_requester_idx').on(t.requesterId),
    index('friendships_addressee_idx').on(t.addresseeId),
    check('friendships_not_self', sql`${t.requesterId} <> ${t.addresseeId}`),
    // ADR 0002: one friendship per *unordered* pair. LEAST/GREATEST canonicalise
    // the pair so A→B and B→A collide; the partial predicate lets declined
    // tombstones and soft-deleted rows coexist with a fresh live row
    // (re-request-after-decline and re-add-after-remove stay legal).
    uniqueIndex('friendships_pair_unique')
      .on(
        sql`least(${t.requesterId}, ${t.addresseeId})`,
        sql`greatest(${t.requesterId}, ${t.addresseeId})`
      )
      .where(sql`${t.status} <> 'declined' AND ${t.deletedAt} IS NULL`),
  ]
);

export const pacts = pgTable(
  'pacts',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    creatorUserId: text('creator_user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    keeperUserId: text('keeper_user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    title: text('title').notNull(),
    description: text('description'),
    type: pactType('type').notNull(),
    status: pactStatus('status').default('active').notNull(),
    startDate: date('start_date', { mode: 'string' }).notNull(),
    endDate: date('end_date', { mode: 'string' }).notNull(),
    /** frequency pacts: 0 = Sunday … 6 = Saturday; null = every day */
    daysOfWeek: smallint('days_of_week').array(),
    goalTarget: integer('goal_target'),
    goalUnit: text('goal_unit'),
    isMutual: boolean('is_mutual').default(false).notNull(),
    /** shared token linking the two twins of a mutual pact */
    mutualPactId: uuid('mutual_pact_id'),
    tintIndex: integer('tint_index').default(0).notNull(),
    ...timestamps,
  },
  (t) => [
    index('pacts_creator_idx').on(t.creatorUserId),
    index('pacts_keeper_idx').on(t.keeperUserId),
    index('pacts_mutual_idx').on(t.mutualPactId),
  ]
);

export const checkIns = pgTable(
  'check_ins',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    pactId: uuid('pact_id')
      .notNull()
      .references(() => pacts.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    /** local date key in the user's timezone at the moment of sealing */
    date: date('date', { mode: 'string' }).notNull(),
    status: checkInStatus('status').notNull(),
    progressValue: doublePrecision('progress_value'),
    /** IANA timezone the check-in was recorded in */
    timezone: text('timezone').notNull(),
    // immutable: no updated_at
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [uniqueIndex('check_ins_pact_user_date_unique').on(t.pactId, t.userId, t.date)]
);

export const notifications = pgTable(
  'notifications',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    type: notificationType('type').notNull(),
    title: text('title').notNull(),
    body: text('body').notNull(),
    sentAt: timestamp('sent_at', { withTimezone: true }).defaultNow().notNull(),
    readAt: timestamp('read_at', { withTimezone: true }),
    pactId: uuid('pact_id').references(() => pacts.id, { onDelete: 'set null' }),
    friendId: text('friend_id').references(() => user.id, { onDelete: 'set null' }),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [index('notifications_user_idx').on(t.userId, t.readAt)]
);
